version: "3.3"

services:
  db:
    image: postgres:15.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "8080:5432"

volumes:
  data:
